name: Sync production to main

on:
  push:
    branches:
      - production

jobs:
  sync-production-to-main:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout main branch
        uses: actions/checkout@v4
        with:
          ref: main

      - name: Reset branch
        run: |
          git fetch origin production:production
          git reset --hard production

      - name: Create pull request
        uses: peter-evans/create-pull-request@v7
        with:
          token: ${{ secrets.PAT_TOKEN }}
          commit-message: 'chore: sync production to main'
          title: 'Sync production to main'
          body: 'Automated PR to sync `production` branch to `main` branch'
          branch: sync-production-to-main
          base: main
          labels: |
            automated
            sync
